### ISSUE TITLE
Compatibility Ninja Forms Save Progress add-on

### ISSUE THREAD

**Issue by LeoOosterloo** [pronamic/wp-pronamic-pay-ninjaforms#8] opened 2023-08-08 12:50 UTC
> When someone fills in the form that contains the pay redirect and someone then clicks on save and then wants to submit the form later, the paywall no longer works.
> Ninja Forms says it can't do anything with it and refers us to you.
> 
> Would love to hear what you can do

and

> Pronamic creates a payment when you click on the save button (See the image with the buttons on it that I sent in the 1st email) This should actually only happen when you click on send final application.

From internal support ticket: https://secure.helpscout.net/conversation/2323763485/25998

**Comment by remcotolsma** [comment] 2023-09-27 11:45
We could not reproduce this issue, in Dutch:

> Ik kan geen probleem reproduceren met de Save Progress add-on.
> 
> Is de "Collect payment"-actie (Betaling innen) misschien per ongeluk ook ingeschakeld voor het "Save" event in de instellingen van het formulier (zie screenshot)?
> 
> <img width="913" alt="Scherm-afbeelding-2023-08-24-om-16-12-44" src="https://github.com/pronamic/wp-pronamic-pay-ninjaforms/assets/869674/e3dcab1b-8c66-4508-8c80-0349c72bbf72">

The customer who encountered the issue did not reply back, we will close this issue as 'can't repro'.

**Closed by remcotolsma** 2023-09-27 11:45 UTC
Labels: enhancement
